(load "lib.scm")

(define (make-sparse-keymap)
  (make-eq-hashtable))

(define (define-key k map cmd)
  (cond ((char? k) (hashtable-set! map (char->integer k) cmd))
        ((integer? k) (hashtable-set! map k cmd))))

(define (lookup-keymap k map)
  (if (hashtable-contains? map k)
      (let ((f (hashtable-ref map k 0)))
        (cond
         ((procedure? f)
          (f)
          ;;(editorSetStatusMessage "HELP: Ctrl-S = save | Ctrl-Q = quit | Ctrl-F = find")
          (set! current-keymap global-keymap))
         ((hashtable? f)
          (set! current-keymap f))))
      (begin
       (editorSetStatusMessage "keys not found")
       (set! current-keymap global-keymap))))

(define current-keymap)
(define global-keymap (make-sparse-keymap))
(define C-x-keymap (make-sparse-keymap))

(define (bind-chars-self-insert-command)
  (letrec ((start 32)
           (end 126)
           (bind-char-self-insert-command (lambda (c)
                                            (define-key c global-keymap (lambda () (self-insert-command c)))
                                            (unless (= c end)
                                              (bind-char-self-insert-command (+ c 1))))))
    (bind-char-self-insert-command start)))

(bind-chars-self-insert-command)

;; (define-key (CTRL_KEY #\q) global-keymap quit)
(define-key (CTRL_KEY #\s) global-keymap find)
(define-key (CTRL_KEY #\a) global-keymap move-beginning-of-line)
(define-key (CTRL_KEY #\e) global-keymap move-end-of-line)
(define-key (CTRL_KEY #\n) global-keymap next-line)
(define-key (CTRL_KEY #\p) global-keymap previous-line)
(define-key (CTRL_KEY #\f) global-keymap forward-char)
(define-key (CTRL_KEY #\b) global-keymap backward-char)
(define-key (CTRL_KEY #\d) global-keymap delete-char)
(define-key (CTRL_KEY #\k) global-keymap kill-line)
(define-key (CTRL_KEY #\m) global-keymap newline)
(define-key (CTRL_KEY #\o) global-keymap open-line)
(define-key (CTRL_KEY #\i) global-keymap (lambda () (self-insert-command 9)))
(define-key BACKSPACE global-keymap backward-delete-char)
(define-key DEL_KEY global-keymap delete-char)

(define-key (CTRL_KEY #\v) global-keymap scroll-down-command)
(define-key (ALT_KEY #\v) global-keymap scroll-up-command)

(define-key (CTRL_KEY #\x) global-keymap C-x-keymap)
(define-key (CTRL_KEY #\s) C-x-keymap save-file)
(define-key (CTRL_KEY #\c) C-x-keymap quit)
(define-key (CTRL_KEY #\e) C-x-keymap eval-last-sexp)
(define-key (ALT_KEY #\x) global-keymap execute-command)
(define-key (ALT_KEY #\f) global-keymap forward-word)
(define-key (ALT_KEY #\b) global-keymap backward-word)
